### ISSUE TITLE
Azure branch kérdés

### ISSUE THREAD

**Issue by Gomboc7** [cloudsteak/trn-node-demo#102]
Szia Tibor!

Azért írok mert sikerült lefolk-olni a https://github.com/cloudsteak/trn-node-demo oldalt, a https://github.com/Gomboc7/trn-node-demo -ra, saját repository-t csinálni.
Ezt sikerült is telepítenem Azure-ba.
Viszont amikor módosítani akartam egy saját Branch-en, akkor azt nem tudom befuttatni a main-omba, hanem folyton az eredeti cloudsteak-os main-ba akarja csak pull-olni. Itt van is pár request-em, ahol látható, hogy próbálom, de nyilván nem oda akarom... de nem találom hogy kell a sajátomba...

Üdv,
Laci

**Comment by the1bit** [comment]
Szia,

Csak annyit kell tenned, hogy amikor indítod az összefűzési kérést (Pull Request), akkor a `Comparing changes` felirat alatt a cél repositiry és branch, az a sajátod legyen. `Gomboc7/trn-node-demo` - `main`.

![Screenshot 2024-11-12 at 14 43 35](https://github.com/user-attachments/assets/403e3c39-7720-4a30-9f5d-151f66be7c8d)

![Screenshot 2024-11-12 at 14 45 08](https://github.com/user-attachments/assets/c83b5642-8549-4a6c-9d90-573823bd82d6)

**Comment by Gomboc7** [comment]
Köszi, megváltoztattam a repository-t a sajátra.
Viszont most meg olyan hiba jött elő, amire csak pislogni tudok:
![image](https://github.com/user-attachments/assets/7b26bab4-bb8b-4e1b-97ff-b61fec2e8a07)
![image](https://github.com/user-attachments/assets/4a445355-150d-4d5a-9f5f-328c7ca840cf)
"##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request"
Ez mit jelent? Mi az a hosted parallelism?

**Comment by the1bit** [comment]
A `hosted parallelism` az a pipeline-ok egyidejű futása. De ez nem feltétlenül jelent semmit jelen esetben.
Mivel saját Azure DevOps projectben csináltad meg, így nem tudom megnézni mi a pontos probléma. 

Nem tudnád megcsinálni abban, amit a képzésen használunk?

Köszi

**Comment by Gomboc7** [comment]
Hogyan csináljam? A DevOps verzióra emlékszem, amit mutattál a másikra nem.
Szerintem az volt a baj, hogy két service connection-om volt. Egy Oauth-os, meg egy tokenes.
Most működik.

**Comment by the1bit** [comment]
Szuper. :-)

Örülök.

Ezt használtuk a képzésen (van hozzá jogod is, ha igényeltél Azure hozzáférést): https://cloudsteak.visualstudio.com/MentorKlub

**Comment by Gomboc7** [comment]
Nincs ide hozzáférésem, hol lehet igényelni?

Tibor Kiss ***@***.***> ezt írta (időpont: 2024. nov. 12., K,
17:20):

**Comment by the1bit** [comment]
A több hetes képzés oldalán megtalálsz minden információt hozzá. :-)
