### ISSUE TITLE
mentor-app-linux, írási jog

### ISSUE THREAD

**Issue by csjanos1** [cloudsteak/trn-node-demo#15]
Kedves Tibor,
sajnos a portálon belül nincs hozzáférésem ahhoz, hogy egy új web alkalmazásban a mentor-app-linux csoportot
válasszam hozzá (nincs írási jogom). Saját tokennel dolgoztam, lehet hogy ez a baj?
Üdvözlettel
Csörge János

**Comment by the1bit** [comment]
Szia,

Teljesen igazad van. Nem adtam jogot rá. Hamarosan azonban kaptok jogot a megfelelő App Plan-ra.

Üdv:
tibi
